services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  app:
    image: urkoren/pokemon-shop:latest
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      SESSION_TYPE: "redis"
      SESSION_PERMANENT: "True"
      SESSION_USE_SIGNER: "True"
      SESSION_KEY_PREFIX: "pokemon-shop:"
      SESSION_REDIS: "redis://redis:6379/0"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      API_KEY: "${API_KEY}"
      ADMIN_MAIL: "${ADMIN_MAIL}"
      PYTHONPATH: "./"
    volumes:
      - ./migrations:/app/migrations

  test:
    build: .
    depends_on:
      - app
    environment:
      FLASK_ENV: testing
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      API_KEY: "${API_KEY}"
      ADMIN_MAIL: "${ADMIN_MAIL}"
      PYTHONPATH: "./"
    volumes:
      - /home/ec2-user/git/pokemon-shop/test-results:/app/test-results
    command: pytest --junitxml=/app/test-results/results.xml -q

