CITIES_IN_ISRAEL = [
    "Afula",
    "Arad",
    "Ariel",
    "Ashdod",
    "Ashkelon",
    "Baqa al-Gharbiyye",
    "Bat Yam",
    "Be'er Sheva",
    "Beit She'an",
    "Beit Shemesh",
    "Bnei Brak",
    "Dimona",
    "Eilat",
    "Elad",
    "Givatayim",
    "Giv'at Shmuel",
    "Hadera",
    "Haifa",
    "Herzliya",
    "Hod HaSharon",
    "Holon",
    "Jerusalem",
    "Karmiel",
    "Kiryat Ata",
    "Kiryat Bialik",
    "Kiryat Gat",
    "Kiryat Malakhi",
    "Kiryat Motzkin",
    "Kiryat Ono",
    "Kiryat Shmona",
    "Kiryat Yam",
    "Lod",
    "Ma'alot-Tarshiha",
    "Ma'ale Adumim",
    "Migdal HaEmek",
    "Modiin-Maccabim-Reut",
    "Nahariya",
    "Nazareth",
    "Nazareth Illit (Nof HaGalil)",
    "Netanya",
    "Netivot",
    "Ofakim",
    "Or Akiva",
    "Or Yehuda",
    "Petah Tikva",
    "Qalansawe",
    "Raanana",
    "Ramat Gan",
    "Ramat HaSharon",
    "Ramla",
    "Rehovot",
    "Rishon LeZion",
    "Rosh HaAyin",
    "Sakhnin",
    "Sderot",
    "Shefa-Amr",
    "Tamra",
    "Tel Aviv",
    "Tiberias",
    "Tirat Carmel",
    "Umm al-Fahm",
    "Yavne",
    "Yehud-Monosson",
    "Yokneam",
    "Zefat (Safed)",
]
