"""Added is active for account

Revision ID: 0119ff80443f
Revises: 4ad3dbfe0aa3
Create Date: 2025-01-10 14:17:39.960107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0119ff80443f'
down_revision = '4ad3dbfe0aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('back_image_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=251),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('back_image_url',
               existing_type=sa.String(length=251),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
