"""Add is_read flag to Message model

Revision ID: 2ce3bd4f19cd
Revises: b5c2c9d6a024
Create Date: 2024-12-18 10:58:29.168094

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ce3bd4f19cd"
down_revision = "b5c2c9d6a024"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_read", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("is_read")

    # ### end Alembic commands ###
