"""Add follow_tcg to Card

Revision ID: f5f2effbaa18
Revises: c797358a5b57
Create Date: 2024-12-09 19:38:23.403438

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5f2effbaa18"
down_revision = "c797358a5b57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.add_column(sa.Column("follow_tcg", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.drop_column("follow_tcg")

    # ### end Alembic commands ###
