name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install Dependencies
        run: |
          pip install flake8
      - name: Run Linting
        run: |
          flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: |
          docker-compose up --build test


  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pokemon-shop:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pokemon-shop:latest

  # deploy:
  #   name: Deploy to EC2
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USER }}
  #         key: ${{ secrets.EC2_PRIVATE_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/pokemon-shop:latest
  #           docker stop pokemon-shop || true
  #           docker rm pokemon-shop || true
  #           docker run -d -p 5000:5000 --name pokemon-shop ${{ secrets.DOCKER_USERNAME }}/pokemon-shop:latest

